version: '3.8'

volumes:
  db_data:

services:
  db:
    image: postgres:14.1
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rootssl
      POSTGRES_PASSWORD: rootsll
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'